name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.0

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze .

      - name: Run tests
        run: flutter test

      - name: Setup Pub Credentials
        run: |
          echo "export PUB_DEV_PUBLISH_ACCESS_TOKEN=$PUB_DEV_PUBLISH_ACCESS_TOKEN" >> $GITHUB_ENV
          echo "export PUB_DEV_PUBLISH_REFRESH_TOKEN=$PUB_DEV_PUBLISH_REFRESH_TOKEN" >> $GITHUB_ENV (optional, if using refresh token)

      - name: Check Publish Warnings
        run: dart pub publish --dry-run

      - name: Publish Package
        run: dart pub publish -f